/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CompanyId = IDL.Text;
export const Company = IDL.Record({
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'activeStatus' : IDL.Variant({ 'Inactive' : IDL.Null, 'Active' : IDL.Null }),
  'companyName' : IDL.Text,
  'companyId' : CompanyId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateCompany' : IDL.Func([], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyInfo' : IDL.Func([], [IDL.Opt(Company)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetYearProgressData' : IDL.Func([IDL.Text], [], []),
  'updateCompanyName' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CompanyId = IDL.Text;
  const Company = IDL.Record({
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'activeStatus' : IDL.Variant({
      'Inactive' : IDL.Null,
      'Active' : IDL.Null,
    }),
    'companyName' : IDL.Text,
    'companyId' : CompanyId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateCompany' : IDL.Func([], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyInfo' : IDL.Func([], [IDL.Opt(Company)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetYearProgressData' : IDL.Func([IDL.Text], [], []),
    'updateCompanyName' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };