/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RoleAssignment {
    orgNodeId?: OrgNodeId;
    roleType: Variant_DivisionHead_Director_PresidentDirector_DepartmentHead_CompanyAdmin;
    assignedAt: bigint;
    assignedBy: Principal;
    userId: UserId;
    activeStatus: boolean;
    ultimateParentId?: string;
    assignmentId: RoleAssignmentId;
    parentId?: string;
    grandParentId?: string;
    companyId: CompanyId;
}
export type RoleAssignmentId = string;
export type RegistrationCode = string;
export interface KPIYear {
    status: Variant_Open_Closed;
    kpiYearId: KPIYearId;
    createdAt: bigint;
    createdBy: Principal;
    year: bigint;
    companyId: CompanyId;
}
export interface StrategicObjective {
    createdAt: bigint;
    createdBy: Principal;
    objectiveId: StrategicObjectiveId;
    bscAspectId: BSCAspectId;
    objectiveName: string;
    companyId: CompanyId;
}
export type StrategicObjectiveId = string;
export interface User {
    status: Variant_Inactive_Active_Unassigned;
    userId: UserId;
    createdAt: bigint;
    createdBy: Principal;
    fullName: string;
    emailAddress?: string;
    registrationCodeUsed?: string;
    principalId: Principal;
    companyId: CompanyId;
}
export interface KPI {
    strategicObjectiveId: string;
    kpiMeasurement: string;
    kpiYearId: string;
    createdAt: bigint;
    createdBy: Principal;
    ownerRoleAssignmentId: string;
    kpiWeight: number;
    kpiStatus: Variant_Approved_Draft_Submitted_Revised;
    updatedAt: bigint;
    updatedBy: Principal;
    approverUserId?: string;
    kpiPeriod: Variant_OneTime_Quarterly_Monthly_SemiAnnual_Annual;
    bscAspectId: string;
    kpiId: KPIId;
    organizationNodeId: string;
    companyId: CompanyId;
}
export type KPIYearId = string;
export interface BSCAspect {
    createdAt: bigint;
    createdBy: Principal;
    aspectId: BSCAspectId;
    aspectName: string;
    companyId: CompanyId;
}
export interface AuditLog {
    action: string;
    auditId: AuditId;
    entityId: string;
    performedBy: Principal;
    timestamp: bigint;
    entityType: string;
    companyId: CompanyId;
}
export interface MyProfile {
    status: Variant_Inactive_Active_Unassigned;
    userId: UserId;
    fullName: string;
    principalId: Principal;
    roles: Array<RoleAssignment>;
    companyId: CompanyId;
}
export type BSCAspectId = string;
export type AuditId = string;
export type UserId = string;
export type CompanyId = string;
export type KPIId = string;
export interface OrgNode {
    nodeId: OrgNodeId;
    parentNodeId?: OrgNodeId;
    createdAt: bigint;
    createdBy: Principal;
    updatedAt: bigint;
    updatedBy: Principal;
    nodeName: string;
    nodeType: Variant_Division_Director_PresidentDirector_Department;
    companyId: CompanyId;
}
export type OrgNodeId = string;
export interface RegistrationCodeRecord {
    code: string;
    createdAt: bigint;
    createdBy: Principal;
    isActive: boolean;
    companyId: string;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Approved_Draft_Submitted_Revised {
    Approved = "Approved",
    Draft = "Draft",
    Submitted = "Submitted",
    Revised = "Revised"
}
export enum Variant_DivisionHead_Director_PresidentDirector_DepartmentHead_CompanyAdmin {
    DivisionHead = "DivisionHead",
    Director = "Director",
    PresidentDirector = "PresidentDirector",
    DepartmentHead = "DepartmentHead",
    CompanyAdmin = "CompanyAdmin"
}
export enum Variant_Division_Director_PresidentDirector_Department {
    Division = "Division",
    Director = "Director",
    PresidentDirector = "PresidentDirector",
    Department = "Department"
}
export enum Variant_Inactive_Active_Unassigned {
    Inactive = "Inactive",
    Active = "Active",
    Unassigned = "Unassigned"
}
export enum Variant_OneTime_Quarterly_Monthly_SemiAnnual_Annual {
    OneTime = "OneTime",
    Quarterly = "Quarterly",
    Monthly = "Monthly",
    SemiAnnual = "SemiAnnual",
    Annual = "Annual"
}
export enum Variant_Open_Closed {
    Open = "Open",
    Closed = "Closed"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveKPI(kpiId: KPIId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRole(userId: UserId, roleType: string, organizationNodeId: string | null): Promise<void>;
    createBSCAspect(aspectName: string): Promise<BSCAspectId>;
    createCompany(companyName: string, adminFullName: string, email: string | null): Promise<CompanyId>;
    createKPI(kpiYearId: string, bscAspectId: string, strategicObjectiveId: string, organizationNodeId: string, kpiMeasurement: string, kpiPeriod: string, kpiWeight: number): Promise<KPIId>;
    createKPIYear(year: bigint): Promise<KPIYearId>;
    createOKR(okrYearId: string, okrAspect: string, objective: string, keyResult: string, initialTargetDate: string): Promise<string>;
    createOrganizationNode(nodeType: string, nodeName: string, parentNodeId: string | null): Promise<OrgNodeId>;
    createStrategicObjective(bscAspectId: BSCAspectId, objectiveName: string): Promise<StrategicObjectiveId>;
    deactivateRegistrationCode(code: string): Promise<void>;
    deactivateRoleAssignment(assignmentId: RoleAssignmentId): Promise<void>;
    generateRegistrationCode(): Promise<RegistrationCode>;
    getAuditLogs(entityType: string | null, entityId: string | null): Promise<Array<AuditLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getKPI(kpiId: KPIId): Promise<KPI | null>;
    getMyProfile(): Promise<MyProfile | null>;
    getOKR(okrId: string): Promise<string | null>;
    getUserById(userId: UserId): Promise<User | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinCompany(code: string, fullName: string, email: string | null): Promise<CompanyId>;
    listBSCAspects(): Promise<Array<BSCAspect>>;
    listKPIYears(): Promise<Array<KPIYear>>;
    listKPIs(kpiYearId: string | null, organizationNodeId: string | null, statusFilter: string | null): Promise<Array<KPI>>;
    listOrganizationNodes(): Promise<Array<OrgNode>>;
    listRegistrationCodes(): Promise<Array<RegistrationCodeRecord>>;
    listRoleAssignments(userId: UserId | null): Promise<Array<RoleAssignment>>;
    listStrategicObjectives(bscAspectId: BSCAspectId | null): Promise<Array<StrategicObjective>>;
    listUsers(): Promise<Array<User>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setKPIYearStatus(kpiYearId: KPIYearId, newStatus: string): Promise<void>;
    submitKPI(kpiId: KPIId): Promise<void>;
    updateBSCAspect(aspectId: BSCAspectId, aspectName: string): Promise<void>;
    updateKPIProgress(kpiId: KPIId, periodIndex: bigint, achievement: number): Promise<void>;
    updateOrganizationNode(nodeId: OrgNodeId, nodeName: string): Promise<void>;
    updateStrategicObjective(objectiveId: StrategicObjectiveId, objectiveName: string): Promise<void>;
    updateUserStatus(userId: UserId, newStatus: string): Promise<void>;
}
import type { BSCAspectId as _BSCAspectId, CompanyId as _CompanyId, KPI as _KPI, KPIId as _KPIId, KPIYear as _KPIYear, KPIYearId as _KPIYearId, MyProfile as _MyProfile, OrgNode as _OrgNode, OrgNodeId as _OrgNodeId, RoleAssignment as _RoleAssignment, RoleAssignmentId as _RoleAssignmentId, User as _User, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveKPI(arg0: KPIId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveKPI(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveKPI(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRole(arg0: UserId, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createBSCAspect(arg0: string): Promise<BSCAspectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBSCAspect(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBSCAspect(arg0);
            return result;
        }
    }
    async createCompany(arg0: string, arg1: string, arg2: string | null): Promise<CompanyId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCompany(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCompany(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createKPI(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: number): Promise<KPIId> {
        if (this.processError) {
            try {
                const result = await this.actor.createKPI(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createKPI(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createKPIYear(arg0: bigint): Promise<KPIYearId> {
        if (this.processError) {
            try {
                const result = await this.actor.createKPIYear(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createKPIYear(arg0);
            return result;
        }
    }
    async createOKR(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createOKR(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOKR(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createOrganizationNode(arg0: string, arg1: string, arg2: string | null): Promise<OrgNodeId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrganizationNode(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrganizationNode(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createStrategicObjective(arg0: BSCAspectId, arg1: string): Promise<StrategicObjectiveId> {
        if (this.processError) {
            try {
                const result = await this.actor.createStrategicObjective(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStrategicObjective(arg0, arg1);
            return result;
        }
    }
    async deactivateRegistrationCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateRegistrationCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateRegistrationCode(arg0);
            return result;
        }
    }
    async deactivateRoleAssignment(arg0: RoleAssignmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateRoleAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateRoleAssignment(arg0);
            return result;
        }
    }
    async generateRegistrationCode(): Promise<RegistrationCode> {
        if (this.processError) {
            try {
                const result = await this.actor.generateRegistrationCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateRegistrationCode();
            return result;
        }
    }
    async getAuditLogs(arg0: string | null, arg1: string | null): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKPI(arg0: KPIId): Promise<KPI | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKPI(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKPI(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<MyProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOKR(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOKR(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOKR(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: UserId): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinCompany(arg0: string, arg1: string, arg2: string | null): Promise<CompanyId> {
        if (this.processError) {
            try {
                const result = await this.actor.joinCompany(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinCompany(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async listBSCAspects(): Promise<Array<BSCAspect>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBSCAspects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBSCAspects();
            return result;
        }
    }
    async listKPIYears(): Promise<Array<KPIYear>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKPIYears();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKPIYears();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listKPIs(arg0: string | null, arg1: string | null, arg2: string | null): Promise<Array<KPI>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKPIs(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKPIs(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrganizationNodes(): Promise<Array<OrgNode>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrganizationNodes();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrganizationNodes();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRegistrationCodes(): Promise<Array<RegistrationCodeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRegistrationCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRegistrationCodes();
            return result;
        }
    }
    async listRoleAssignments(arg0: UserId | null): Promise<Array<RoleAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRoleAssignments(to_candid_opt_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRoleAssignments(to_candid_opt_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStrategicObjectives(arg0: BSCAspectId | null): Promise<Array<StrategicObjective>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStrategicObjectives(to_candid_opt_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStrategicObjectives(to_candid_opt_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setKPIYearStatus(arg0: KPIYearId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setKPIYearStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setKPIYearStatus(arg0, arg1);
            return result;
        }
    }
    async submitKPI(arg0: KPIId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKPI(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKPI(arg0);
            return result;
        }
    }
    async updateBSCAspect(arg0: BSCAspectId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBSCAspect(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBSCAspect(arg0, arg1);
            return result;
        }
    }
    async updateKPIProgress(arg0: KPIId, arg1: bigint, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKPIProgress(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKPIProgress(arg0, arg1, arg2);
            return result;
        }
    }
    async updateOrganizationNode(arg0: OrgNodeId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrganizationNode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrganizationNode(arg0, arg1);
            return result;
        }
    }
    async updateStrategicObjective(arg0: StrategicObjectiveId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStrategicObjective(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStrategicObjective(arg0, arg1);
            return result;
        }
    }
    async updateUserStatus(arg0: UserId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_KPIYear_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KPIYear): KPIYear {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_KPI_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KPI): KPI {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_MyProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MyProfile): MyProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_OrgNode_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrgNode): OrgNode {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_RoleAssignment_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoleAssignment): RoleAssignment {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_User_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MyProfile]): MyProfile | null {
    return value.length === 0 ? null : from_candid_MyProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrgNodeId]): OrgNodeId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KPI]): KPI | null {
    return value.length === 0 ? null : from_candid_KPI_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        Inactive: null;
    } | {
        Active: null;
    } | {
        Unassigned: null;
    };
    userId: _UserId;
    fullName: string;
    principalId: Principal;
    roles: Array<_RoleAssignment>;
    companyId: _CompanyId;
}): {
    status: Variant_Inactive_Active_Unassigned;
    userId: UserId;
    fullName: string;
    principalId: Principal;
    roles: Array<RoleAssignment>;
    companyId: CompanyId;
} {
    return {
        status: from_candid_variant_n16(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        fullName: value.fullName,
        principalId: value.principalId,
        roles: from_candid_vec_n17(_uploadFile, _downloadFile, value.roles),
        companyId: value.companyId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orgNodeId: [] | [_OrgNodeId];
    roleType: {
        DivisionHead: null;
    } | {
        Director: null;
    } | {
        PresidentDirector: null;
    } | {
        DepartmentHead: null;
    } | {
        CompanyAdmin: null;
    };
    assignedAt: bigint;
    assignedBy: Principal;
    userId: _UserId;
    activeStatus: boolean;
    ultimateParentId: [] | [string];
    assignmentId: _RoleAssignmentId;
    parentId: [] | [string];
    grandParentId: [] | [string];
    companyId: _CompanyId;
}): {
    orgNodeId?: OrgNodeId;
    roleType: Variant_DivisionHead_Director_PresidentDirector_DepartmentHead_CompanyAdmin;
    assignedAt: bigint;
    assignedBy: Principal;
    userId: UserId;
    activeStatus: boolean;
    ultimateParentId?: string;
    assignmentId: RoleAssignmentId;
    parentId?: string;
    grandParentId?: string;
    companyId: CompanyId;
} {
    return {
        orgNodeId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.orgNodeId)),
        roleType: from_candid_variant_n21(_uploadFile, _downloadFile, value.roleType),
        assignedAt: value.assignedAt,
        assignedBy: value.assignedBy,
        userId: value.userId,
        activeStatus: value.activeStatus,
        ultimateParentId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.ultimateParentId)),
        assignmentId: value.assignmentId,
        parentId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.parentId)),
        grandParentId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.grandParentId)),
        companyId: value.companyId
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        Inactive: null;
    } | {
        Active: null;
    } | {
        Unassigned: null;
    };
    userId: _UserId;
    createdAt: bigint;
    createdBy: Principal;
    fullName: string;
    emailAddress: [] | [string];
    registrationCodeUsed: [] | [string];
    principalId: Principal;
    companyId: _CompanyId;
}): {
    status: Variant_Inactive_Active_Unassigned;
    userId: UserId;
    createdAt: bigint;
    createdBy: Principal;
    fullName: string;
    emailAddress?: string;
    registrationCodeUsed?: string;
    principalId: Principal;
    companyId: CompanyId;
} {
    return {
        status: from_candid_variant_n16(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        fullName: value.fullName,
        emailAddress: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.emailAddress)),
        registrationCodeUsed: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.registrationCodeUsed)),
        principalId: value.principalId,
        companyId: value.companyId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        Open: null;
    } | {
        Closed: null;
    };
    kpiYearId: _KPIYearId;
    createdAt: bigint;
    createdBy: Principal;
    year: bigint;
    companyId: _CompanyId;
}): {
    status: Variant_Open_Closed;
    kpiYearId: KPIYearId;
    createdAt: bigint;
    createdBy: Principal;
    year: bigint;
    companyId: CompanyId;
} {
    return {
        status: from_candid_variant_n28(_uploadFile, _downloadFile, value.status),
        kpiYearId: value.kpiYearId,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        year: value.year,
        companyId: value.companyId
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nodeId: _OrgNodeId;
    parentNodeId: [] | [_OrgNodeId];
    createdAt: bigint;
    createdBy: Principal;
    updatedAt: bigint;
    updatedBy: Principal;
    nodeName: string;
    nodeType: {
        Division: null;
    } | {
        Director: null;
    } | {
        PresidentDirector: null;
    } | {
        Department: null;
    };
    companyId: _CompanyId;
}): {
    nodeId: OrgNodeId;
    parentNodeId?: OrgNodeId;
    createdAt: bigint;
    createdBy: Principal;
    updatedAt: bigint;
    updatedBy: Principal;
    nodeName: string;
    nodeType: Variant_Division_Director_PresidentDirector_Department;
    companyId: CompanyId;
} {
    return {
        nodeId: value.nodeId,
        parentNodeId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.parentNodeId)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        updatedAt: value.updatedAt,
        updatedBy: value.updatedBy,
        nodeName: value.nodeName,
        nodeType: from_candid_variant_n33(_uploadFile, _downloadFile, value.nodeType),
        companyId: value.companyId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    strategicObjectiveId: string;
    kpiMeasurement: string;
    kpiYearId: string;
    createdAt: bigint;
    createdBy: Principal;
    ownerRoleAssignmentId: string;
    kpiWeight: number;
    kpiStatus: {
        Approved: null;
    } | {
        Draft: null;
    } | {
        Submitted: null;
    } | {
        Revised: null;
    };
    updatedAt: bigint;
    updatedBy: Principal;
    approverUserId: [] | [string];
    kpiPeriod: {
        OneTime: null;
    } | {
        Quarterly: null;
    } | {
        Monthly: null;
    } | {
        SemiAnnual: null;
    } | {
        Annual: null;
    };
    bscAspectId: string;
    kpiId: _KPIId;
    organizationNodeId: string;
    companyId: _CompanyId;
}): {
    strategicObjectiveId: string;
    kpiMeasurement: string;
    kpiYearId: string;
    createdAt: bigint;
    createdBy: Principal;
    ownerRoleAssignmentId: string;
    kpiWeight: number;
    kpiStatus: Variant_Approved_Draft_Submitted_Revised;
    updatedAt: bigint;
    updatedBy: Principal;
    approverUserId?: string;
    kpiPeriod: Variant_OneTime_Quarterly_Monthly_SemiAnnual_Annual;
    bscAspectId: string;
    kpiId: KPIId;
    organizationNodeId: string;
    companyId: CompanyId;
} {
    return {
        strategicObjectiveId: value.strategicObjectiveId,
        kpiMeasurement: value.kpiMeasurement,
        kpiYearId: value.kpiYearId,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        ownerRoleAssignmentId: value.ownerRoleAssignmentId,
        kpiWeight: value.kpiWeight,
        kpiStatus: from_candid_variant_n10(_uploadFile, _downloadFile, value.kpiStatus),
        updatedAt: value.updatedAt,
        updatedBy: value.updatedBy,
        approverUserId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.approverUserId)),
        kpiPeriod: from_candid_variant_n12(_uploadFile, _downloadFile, value.kpiPeriod),
        bscAspectId: value.bscAspectId,
        kpiId: value.kpiId,
        organizationNodeId: value.organizationNodeId,
        companyId: value.companyId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Draft: null;
} | {
    Submitted: null;
} | {
    Revised: null;
}): Variant_Approved_Draft_Submitted_Revised {
    return "Approved" in value ? Variant_Approved_Draft_Submitted_Revised.Approved : "Draft" in value ? Variant_Approved_Draft_Submitted_Revised.Draft : "Submitted" in value ? Variant_Approved_Draft_Submitted_Revised.Submitted : "Revised" in value ? Variant_Approved_Draft_Submitted_Revised.Revised : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OneTime: null;
} | {
    Quarterly: null;
} | {
    Monthly: null;
} | {
    SemiAnnual: null;
} | {
    Annual: null;
}): Variant_OneTime_Quarterly_Monthly_SemiAnnual_Annual {
    return "OneTime" in value ? Variant_OneTime_Quarterly_Monthly_SemiAnnual_Annual.OneTime : "Quarterly" in value ? Variant_OneTime_Quarterly_Monthly_SemiAnnual_Annual.Quarterly : "Monthly" in value ? Variant_OneTime_Quarterly_Monthly_SemiAnnual_Annual.Monthly : "SemiAnnual" in value ? Variant_OneTime_Quarterly_Monthly_SemiAnnual_Annual.SemiAnnual : "Annual" in value ? Variant_OneTime_Quarterly_Monthly_SemiAnnual_Annual.Annual : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
} | {
    Unassigned: null;
}): Variant_Inactive_Active_Unassigned {
    return "Inactive" in value ? Variant_Inactive_Active_Unassigned.Inactive : "Active" in value ? Variant_Inactive_Active_Unassigned.Active : "Unassigned" in value ? Variant_Inactive_Active_Unassigned.Unassigned : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    DivisionHead: null;
} | {
    Director: null;
} | {
    PresidentDirector: null;
} | {
    DepartmentHead: null;
} | {
    CompanyAdmin: null;
}): Variant_DivisionHead_Director_PresidentDirector_DepartmentHead_CompanyAdmin {
    return "DivisionHead" in value ? Variant_DivisionHead_Director_PresidentDirector_DepartmentHead_CompanyAdmin.DivisionHead : "Director" in value ? Variant_DivisionHead_Director_PresidentDirector_DepartmentHead_CompanyAdmin.Director : "PresidentDirector" in value ? Variant_DivisionHead_Director_PresidentDirector_DepartmentHead_CompanyAdmin.PresidentDirector : "DepartmentHead" in value ? Variant_DivisionHead_Director_PresidentDirector_DepartmentHead_CompanyAdmin.DepartmentHead : "CompanyAdmin" in value ? Variant_DivisionHead_Director_PresidentDirector_DepartmentHead_CompanyAdmin.CompanyAdmin : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    Closed: null;
}): Variant_Open_Closed {
    return "Open" in value ? Variant_Open_Closed.Open : "Closed" in value ? Variant_Open_Closed.Closed : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Division: null;
} | {
    Director: null;
} | {
    PresidentDirector: null;
} | {
    Department: null;
}): Variant_Division_Director_PresidentDirector_Department {
    return "Division" in value ? Variant_Division_Director_PresidentDirector_Department.Division : "Director" in value ? Variant_Division_Director_PresidentDirector_Department.Director : "PresidentDirector" in value ? Variant_Division_Director_PresidentDirector_Department.PresidentDirector : "Department" in value ? Variant_Division_Director_PresidentDirector_Department.Department : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoleAssignment>): Array<RoleAssignment> {
    return value.map((x)=>from_candid_RoleAssignment_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KPIYear>): Array<KPIYear> {
    return value.map((x)=>from_candid_KPIYear_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KPI>): Array<KPI> {
    return value.map((x)=>from_candid_KPI_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrgNode>): Array<OrgNode> {
    return value.map((x)=>from_candid_OrgNode_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n23(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BSCAspectId | null): [] | [_BSCAspectId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
